Repository storyofams/next-api-decorators, pull requests merged in 2021-04, with the labels that each got.

#99 [docs] JSDoc for pipes
  lib/pipes/ParameterPipe.ts
  lib/pipes/validators/validateEnum.pipe.ts
  lib/pipes/validators/validation.pipe.ts
Labels: documentation

#65 [docs] intro in readme & table of contents
  README.md
Labels: documentation, status: requires review, status: reviewed

#98 [test] Next.js server
  .github/workflows/test.yaml
  package.json
  test/e2e-download.test.ts
  test/e2e-params.test.ts
  test/e2e-stream.test.ts
  test/e2e.test.ts
  test/setupServer.ts
Labels: enhancement, status: reviewed

#72 [docs] example project
  .eslintignore
  .prettierignore
  example/.babelrc
  example/.gitignore
  example/README.md
  example/data/index.ts
  example/data/users.ts
  example/dto/createUser.input.ts
  example/dto/index.ts
  example/dto/updateUser.input.ts
  example/next-env.d.ts
  example/package.json
  example/pages/api/postman.ts
  example/pages/api/users/[[...params]].ts
  example/pages/index.tsx
  example/postman.json
  example/tsconfig.json
  example/yarn.lock
  lib/internals/handler.ts
  package.json
  tsconfig.build.json
  tsconfig.json
  yarn.lock
Labels: documentation, status: requires review

#103 [docs] updated pipes section in readme
  README.md
Labels: documentation, status: requires review

#116 [feat] log warnings when packages are missing
  README.md
  lib/decorators/httpMethod.decorators.spec.ts
  lib/decorators/httpMethod.decorators.ts
  lib/internals/findRoute.ts
  lib/internals/loadPackage.spec.ts
  lib/internals/loadPackage.ts
  lib/pipes/validators/validation.pipe.spec.ts
  lib/pipes/validators/validation.pipe.ts
Labels: enhancement
